version: 2

models:
  - name: int_orders_margin
    description: calcul de la marge par order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
  - name: int_orders_operational
    description: calcul de la marge opérationnelle par order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
  - name: int_campaigns
    description: infos sur les campagnes de toutes les sources
    columns:
      - name: date_date
        description: date_date
      - name: paid_source
        description: source (adwords, facebook,...)
      - name: campaign_key
        description: clé de la campagne
      - name: campaign_name
        description: nom de la campagne
      - name: ads_cost
        description: coût de la campagne ce jour là
      - name: impression
        description: nombre d'impressions
      - name: click
        description: nombre de clicks